version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@toplocs.com
      PGADMIN_DEFAULT_PASSWORD: postgres
